# Horny Toad Examples Makefile
# jsp Fri Feb  6 17:13:07 CST 2009

CCFILES=$(shell ls -1 *.cc)
TARGETS=$(basename $(CCFILES))
INCLUDEPATH=..
DEPENDPATH=..
EXTRA_SOURCES=../argv.cc
LIBS=-lfftw3

include ../../Makefile.examples
