######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 24 14:33:52 2011
######################################################################

TEMPLATE = app
TARGET = minimal_example
INCLUDEPATH += .

# Input
SOURCES += minimal_example.cc
