######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 24 14:33:53 2011
######################################################################

TEMPLATE = app
TARGET = touch_example
INCLUDEPATH += .

# Input
SOURCES += touch_example.cc
